-- [Supabase SQL Editor에서 실행해주세요]
-- 1. 현장명 관리 테이블 생성
CREATE TABLE IF NOT EXISTS site_names (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 기존 현장 데이터가 있다면 자동으로 마이그레이션 (선택 사항)
INSERT INTO site_names (name)
SELECT DISTINCT session_name FROM active_tasks
ON CONFLICT (name) DO NOTHING;

-- 3. RLS(보안 정책) 비활성화 (테스트 앱용으로 간편한 접근 허용)
ALTER TABLE site_names DISABLE ROW LEVEL SECURITY;
