-- =========================================================================
-- [안티그래비티] IWP 통합 DB 마스터 SQL
-- 반복 실행해도 안전하도록 설계 (멱등성 보장)
-- 최종 정리: 2026-04-30
-- =========================================================================


-- =========================================================================
-- SECTION 1: 핵심 운영 테이블
-- =========================================================================

-- 1-1. 작업 카테고리
CREATE TABLE IF NOT EXISTS public.task_categories (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    main_category TEXT NOT NULL,
    sub_category TEXT NOT NULL,
    display_order INT DEFAULT 999,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 1-2. 생산 계획
CREATE TABLE IF NOT EXISTS public.production_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    site_name TEXT,
    task_type TEXT,
    target_quantity INT DEFAULT 0,
    planned_workers INT DEFAULT 1,
    completed_quantity INT DEFAULT 0,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 1-3. 실시간 작업 (active_tasks)
CREATE TABLE IF NOT EXISTS public.active_tasks (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    session_name TEXT NOT NULL,
    task_type TEXT NOT NULL,
    workers INT DEFAULT 1,
    quantity INT DEFAULT 0,
    status TEXT DEFAULT 'paused',
    last_started_at TIMESTAMPTZ,
    accumulated_seconds FLOAT8 DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    accumulated_man_seconds FLOAT8 DEFAULT 0,
    work_history JSONB DEFAULT '[]'::JSONB,
    plan_id UUID REFERENCES public.production_plans(id),
    completed_quantity INT DEFAULT 0,
    parent_id BIGINT REFERENCES public.active_tasks(id)
);

-- 1-4. 작업 로그 (work_logs)
CREATE TABLE IF NOT EXISTS public.work_logs (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    work_date DATE DEFAULT CURRENT_DATE,
    task TEXT NOT NULL,
    workers INT,
    quantity INT,
    duration FLOAT8,
    memo TEXT,
    applied_wage INT,
    plan_id UUID,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 1-5. 시스템 설정
CREATE TABLE IF NOT EXISTS public.system_config (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- 1-6. 현장명 관리
CREATE TABLE IF NOT EXISTS public.site_names (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- =========================================================================
-- SECTION 2: 창고 관리 테이블
-- =========================================================================

-- 2-1. 재고 마스터
CREATE TABLE IF NOT EXISTS public.warehouse_inventory (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    item_name TEXT NOT NULL,
    category TEXT NOT NULL,
    current_quantity INT DEFAULT 0,
    max_capacity INT DEFAULT 1000,
    location_zone TEXT DEFAULT 'A구역',
    unit_type TEXT DEFAULT '개',
    unit_price INT DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2-2. 재고 변동 이력
CREATE TABLE IF NOT EXISTS public.warehouse_history (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    item_id BIGINT REFERENCES public.warehouse_inventory(id) ON DELETE CASCADE,
    item_name TEXT NOT NULL,
    before_quantity INT DEFAULT 0,
    after_quantity INT DEFAULT 0,
    diff_amount INT DEFAULT 0,
    record_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- =========================================================================
-- SECTION 3: RPA 원격 트리거 테이블
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.rpa_commands (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    command_type TEXT NOT NULL DEFAULT 'sync_inventory',
    status TEXT NOT NULL DEFAULT 'pending',
    message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    result_summary TEXT,
    requested_by TEXT DEFAULT 'admin'
);


-- =========================================================================
-- SECTION 4: 컬럼 안전 추가 (이미 존재하면 무시)
-- =========================================================================

ALTER TABLE public.active_tasks ADD COLUMN IF NOT EXISTS parent_id BIGINT REFERENCES public.active_tasks(id);
ALTER TABLE public.active_tasks ADD COLUMN IF NOT EXISTS plan_id UUID REFERENCES public.production_plans(id);
ALTER TABLE public.work_logs ADD COLUMN IF NOT EXISTS plan_id UUID REFERENCES public.production_plans(id);
ALTER TABLE public.task_categories ADD COLUMN IF NOT EXISTS display_order INT DEFAULT 999;


-- =========================================================================
-- SECTION 5: 외래 키 제약 조건 (삭제 시 안전 처리)
-- =========================================================================

-- work_logs → production_plans: 계획 삭제 시 plan_id를 NULL로 자동 설정
ALTER TABLE public.work_logs DROP CONSTRAINT IF EXISTS work_logs_plan_id_fkey;
ALTER TABLE public.work_logs
    ADD CONSTRAINT work_logs_plan_id_fkey
    FOREIGN KEY (plan_id) REFERENCES public.production_plans(id)
    ON DELETE SET NULL;


-- =========================================================================
-- SECTION 6: RLS (Row Level Security) 정책
-- =========================================================================

ALTER TABLE public.task_categories   DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.production_plans  DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.active_tasks      DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_logs         DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_config     DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_names        DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.warehouse_inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.warehouse_history   DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.rpa_commands        DISABLE ROW LEVEL SECURITY;


-- =========================================================================
-- SECTION 7: 필수 기초 데이터
-- =========================================================================

-- 시스템 설정 기본값
INSERT INTO public.system_config (key, value) VALUES
    ('hourly_wage', '10000'),
    ('admin_password', '70077')
ON CONFLICT (key) DO NOTHING;

-- 기존 현장 데이터에서 현장명 자동 이관
INSERT INTO public.site_names (name)
SELECT DISTINCT session_name FROM public.active_tasks
ON CONFLICT (name) DO NOTHING;

-- 창고 샘플 데이터 (최초 1회만 입력, 이미 있으면 무시)
INSERT INTO public.warehouse_inventory (item_name, category, current_quantity, max_capacity, location_zone, unit_type, unit_price)
SELECT * FROM (VALUES
    ('안전모',              '안전장비', 120,  200,   'A구역', '개',   15000),
    ('현장작업복 (L)',       '안전장비', 85,   100,   'A구역', '벌',   35000),
    ('건축용 목재 (규격A)',  '자재',     450,  500,   'B구역', '묶음', 12000),
    ('철근 10mm',           '자재',     7000, 10000, 'B구역', 'kg',   200),
    ('드릴 공구 세트',       '공구',     15,   20,    'C구역', '세트', 85000),
    ('포장용 래핑 필름',     '소모품',   5,    50,    'C구역', '롤',   5000)
) AS v(item_name, category, current_quantity, max_capacity, location_zone, unit_type, unit_price)
WHERE NOT EXISTS (SELECT 1 FROM public.warehouse_inventory LIMIT 1);


-- =========================================================================
-- SECTION 8: 캐시 새로고침 (최하단 1회 실행)
-- =========================================================================

NOTIFY pgrst, 'reload schema';
