-- 현장명 관리 테이블 추가
CREATE TABLE IF NOT EXISTS site_names (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 기존 데이터에서 현장명 추출하여 초기 데이터 삽입 (선택 사항)
INSERT INTO site_names (name)
SELECT DISTINCT session_name FROM active_tasks
ON CONFLICT (name) DO NOTHING;
